# Generated by Django 3.0.5 on 2020-04-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ourservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('rank', models.TextField()),
                ('personality', models.CharField(max_length=140)),
                ('img', models.ImageField(upload_to='team_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='service_name',
            field=models.CharField(max_length=15),
        ),
    ]
