# Generated by Django 3.0.5 on 2020-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200421_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='personality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='carousel_desc',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='image_alt',
            field=models.CharField(max_length=15),
        ),
    ]
