# Generated by Django 3.0.5 on 2020-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200421_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topcarousel',
            name='carousel_desc',
            field=models.CharField(max_length=25),
        ),
    ]
