# Generated by Django 3.0.5 on 2020-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200421_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='carousel_desc',
            field=models.CharField(max_length=35),
        ),
    ]
