# Generated by Django 3.0.5 on 2020-05-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200422_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
